# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 480)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 461, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label1 = QtWidgets.QLabel(self.tab)
        self.label1.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label1.setStyleSheet("font: 75 14pt \"Tlwg Typo\";\n"
"color: rgb(0, 170, 127);")
        self.label1.setObjectName("label1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.label_2.setObjectName("label_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.tab_2)
        self.openGLWidget.setGeometry(QtCore.QRect(60, 70, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 531, 26))
        self.menuBar.setObjectName("menuBar")
        self.menumenu1 = QtWidgets.QMenu(self.menuBar)
        self.menumenu1.setObjectName("menumenu1")
        self.menumenu2 = QtWidgets.QMenu(self.menuBar)
        self.menumenu2.setObjectName("menumenu2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionqweqwe443 = QtWidgets.QAction(MainWindow)
        self.actionqweqwe443.setObjectName("actionqweqwe443")
        self.actionmenu1_1 = QtWidgets.QAction(MainWindow)
        self.actionmenu1_1.setObjectName("actionmenu1_1")
        self.actionmenu2_1 = QtWidgets.QAction(MainWindow)
        self.actionmenu2_1.setObjectName("actionmenu2_1")
        self.actionmenu2_2 = QtWidgets.QAction(MainWindow)
        self.actionmenu2_2.setObjectName("actionmenu2_2")
        self.menumenu1.addSeparator()
        self.menumenu1.addAction(self.actionmenu1_1)
        self.menumenu2.addAction(self.actionmenu2_1)
        self.menumenu2.addAction(self.actionmenu2_2)
        self.menuBar.addAction(self.menumenu1.menuAction())
        self.menuBar.addAction(self.menumenu2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "TextLabel1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menumenu1.setTitle(_translate("MainWindow", "menu1"))
        self.menumenu2.setTitle(_translate("MainWindow", "menu2"))
        self.actionqweqwe443.setText(_translate("MainWindow", "qweqwe443"))
        self.actionmenu1_1.setText(_translate("MainWindow", "menu1-1"))
        self.actionmenu2_1.setText(_translate("MainWindow", "menu2-1"))
        self.actionmenu2_2.setText(_translate("MainWindow", "menu2-2"))
